version: '3.8'
name: monitoring-gra-prometheus
networks:
  monitoring:
    driver: bridge
services:
  prometheus:
    user: root
    image: prom/prometheus:v2.45.6
    container_name: prometheus
    networks:
      - monitoring
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - D:\Projects\dockervolumes\prometheus\prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    restart: no
  grafana:
    image: grafana/grafana-oss:9.5.20
    container_name: grafana
    networks:
      - monitoring
    ports:
      - '3000:3000'
    restart: no
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: node_exporter
    command: '--path.rootfs=/host'
    pid: host
    restart: no
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    command:
      - '-port=8098'
    privileged: true
    restart: no