name: postgresss
services:
  db:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_USER: cacctuccjacc
      POSTGRES_PASSWORD: Klop9090
      POSTGRES_DB: db
    volumes:
      - D:\Projects\dockervolumes\postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: "no"

volumes:
  db-data: