version: "2"
name: rabbitmq
services:
  rabbitmq:
    image: rabbitmq:3.13.6-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - D:\Projects\dockervolumes\rabbit:/var/lib/rabbitmq