extensions:
  health_check:
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      grpc:
      http:  

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 50
    spike_limit_percentage: 30
  
  batch:
    
  attributes:
    actions:
      - key: region
        value: west
        action: insert

exporters:
  debug:
  otlp/jaeger:
    endpoint: "tempo:4317"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true
  datadog:
    api:
      site: us5.datadoghq.com
      key: cfde893d8ce8ead818fc5b031b921fe5

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors: [memory_limiter, attributes, batch]
      exporters:
        - debug
        - otlp/jaeger
        - datadog
    metrics:
      receivers:
        - otlp
      processors: [memory_limiter, batch]
      exporters:
        - debug
        - prometheus
        - datadog
    logs:
      receivers: [otlp]
      processors: []
      exporters: [loki, debug,datadog]

  extensions:
    - health_check
    - zpages